import { useMemo, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { Modal } from '@/components/ui/Modal';
import { Button } from '@/components/ui/Button';
import { Input, Select } from '@/components/ui/Input';
import { Badge } from '@/components/ui/Badge';
import { IoDocumentTextOutline, IoMedkitOutline, IoCalendarOutline, IoFlaskOutline, IoPulseOutline } from 'react-icons/io5';
import { useUiStore } from '@/stores/uiStore';
import { AiTimelineSummarizer } from '@/components/intelligence/AiTimelineSummarizer';
import { ehrService } from '@/services/ehr.service';
import { formatDateTime } from '@/lib/utils';

interface PatientEhrModalProps { open: boolean; onClose: () => void; patientId: string; patientName: string; appointmentId: string; }
const VITAL_KEYS = ['temperature_c','heart_rate_bpm','respiratory_rate_bpm','systolic_bp_mmhg','diastolic_bp_mmhg','oxygen_saturation_pct','weight_kg'] as const;
const VITAL_LABELS: Record<string,string> = { temperature_c:'Temp °C', heart_rate_bpm:'Heart rate', respiratory_rate_bpm:'Respiratory rate', systolic_bp_mmhg:'Systolic BP', diastolic_bp_mmhg:'Diastolic BP', oxygen_saturation_pct:'SpO₂ %', weight_kg:'Weight kg' };

export function PatientEhrModal({ open, onClose, patientId, patientName, appointmentId }: PatientEhrModalProps) {
 const [tab,setTab]=useState<'overview'|'encounter'|'labs'|'prescriptions'>('overview');
 const [title,setTitle]=useState('Clinical encounter'),[diagnosis,setDiagnosis]=useState(''),[notes,setNotes]=useState('');
 const [subjective,setSubjective]=useState(''),[objective,setObjective]=useState(''),[assessment,setAssessment]=useState(''),[carePlan,setCarePlan]=useState('');
 const [followUpAt,setFollowUpAt]=useState(''),[followUpInstructions,setFollowUpInstructions]=useState('');
 const [vitals,setVitals]=useState<Record<string,string>>({}),[rxNotes,setRxNotes]=useState(''),[items,setItems]=useState<any[]>([]);
 const [medQuery,setMedQuery]=useState(''),[selectedMed,setSelectedMed]=useState<{id:string;name:string}|null>(null),[dosage,setDosage]=useState(''),[frequency,setFrequency]=useState(''),[duration,setDuration]=useState('7'),[instructions,setInstructions]=useState('');
 const [labId,setLabId]=useState(''),[priority,setPriority]=useState('standard'),[selectedTests,setSelectedTests]=useState<string[]>([]);
 const toast=useUiStore(s=>s.toast), qc=useQueryClient();
 const context=useQuery({queryKey:['encounter-context',appointmentId],queryFn:()=>ehrService.encounterContext(appointmentId),enabled:open});
 const records=useQuery({queryKey:['ehr',patientId],queryFn:()=>ehrService.records(patientId),enabled:open});
 const reports=useQuery({queryKey:['ehr-labs',patientId],queryFn:()=>ehrService.labReports(patientId),enabled:open&&tab==='labs'});
 const prescriptions=useQuery({queryKey:['ehr-rx',patientId],queryFn:()=>ehrService.prescriptions(patientId),enabled:open&&tab==='prescriptions'});
 const meds=useQuery({queryKey:['medicines',medQuery],queryFn:()=>ehrService.searchMedicines(medQuery),enabled:medQuery.length>2});
 const tests=useQuery({queryKey:['clinical-lab-tests'],queryFn:ehrService.labTests,enabled:open&&tab==='encounter'});
 const labs=useQuery({queryKey:['clinical-laboratories'],queryFn:ehrService.laboratories,enabled:open&&tab==='encounter'});
 const canWrite=context.data?.appointment_status==='checked_in'||context.data?.appointment_status==='in_progress';
 const save=useMutation({mutationFn:ehrService.recordConsultation,onSuccess:()=>{toast('success','Clinical encounter saved');void qc.invalidateQueries({queryKey:['ehr',patientId]});void qc.invalidateQueries({queryKey:['ehr-rx',patientId]});void qc.invalidateQueries({queryKey:['appointments']});setTab('overview');},onError:e=>toast('error',e instanceof Error?e.message:'Could not save encounter')});
 const order=useMutation({mutationFn:ehrService.createLabOrder,onSuccess:()=>{toast('success','Laboratory order created');setSelectedTests([]);},onError:e=>toast('error',e instanceof Error?e.message:'Could not create lab order')});
 const vitalPayload=useMemo(()=>Object.fromEntries(Object.entries(vitals).filter(([,v])=>v.trim()!=='').map(([k,v])=>[k,Number(v)])),[vitals]);
 const allergyRecords=(records.data??[]).filter(r=>r.type==='allergy');
 const timeline=(records.data??[]).map(r=>({date:r.created_at,type:r.title,notes:[r.diagnosis,r.notes].filter(Boolean).join(' — ')}));
 const addMedicine=()=>{if(!selectedMed||!dosage||!frequency)return;setItems(x=>[...x,{medicine_id:selectedMed.id,medicine_name:selectedMed.name,dosage,frequency,duration_days:Math.max(1,Number(duration)||7),instructions}]);setSelectedMed(null);setMedQuery('');setDosage('');setFrequency('');setDuration('7');setInstructions('');};
 const saveEncounter=()=>{if(!canWrite)return toast('error','Move the appointment to checked-in or in-progress first');if(!diagnosis.trim()&&!assessment.trim()&&!notes.trim()&&!carePlan.trim()&&!items.length)return toast('error','Add clinical assessment, diagnosis, notes, care plan, or prescription');save.mutate({appointmentId,title,diagnosis,notes,prescriptionNotes:rxNotes,prescriptionItems:items.map(({medicine_id,dosage,frequency,duration_days,instructions})=>({medicine_id,dosage,frequency,duration_days,instructions})),vitals:vitalPayload,subjectiveNotes:subjective,objectiveNotes:objective,assessmentNotes:assessment,carePlan,followUpAt:followUpAt?new Date(followUpAt).toISOString():null,followUpInstructions});};
 return <Modal open={open} onClose={onClose} title={'Clinical EHR · '+patientName} wide>
  <div className='mb-4 rounded-xl border border-border bg-surface-muted p-4 dark:bg-surface-dark-muted'>
   <div className='flex flex-wrap gap-2'><Badge tone={canWrite?'success':'neutral'}>{context.data?.appointment_status?.replace('_',' ')??'Loading encounter'}</Badge>{context.data?.consultation_type&&<Badge tone='brand'>{context.data.consultation_type}</Badge>}</div>
   <div className='mt-2 grid gap-2 text-xs text-slate-500 sm:grid-cols-2'><span>DHI: {context.data?.digital_health_id??'—'}</span><span>Blood group: {context.data?.blood_group??'—'}</span><span>DOB: {context.data?.dob??'—'}</span><span>Reason: {context.data?.reason??'—'}</span></div>
  </div>
  <div className='flex flex-wrap gap-2 border-b border-border pb-4'><Button size='sm' variant={tab==='overview'?'primary':'secondary'} onClick={()=>setTab('overview')}><IoCalendarOutline/>History</Button><Button size='sm' variant={tab==='encounter'?'primary':'secondary'} onClick={()=>setTab('encounter')}><IoMedkitOutline/>Encounter</Button><Button size='sm' variant={tab==='labs'?'primary':'secondary'} onClick={()=>setTab('labs')}><IoFlaskOutline/>Lab Reports</Button><Button size='sm' variant={tab==='prescriptions'?'primary':'secondary'} onClick={()=>setTab('prescriptions')}><IoDocumentTextOutline/>Prescriptions</Button></div>
  <div className='mt-4 max-h-[65vh] overflow-y-auto pr-1'>
   {tab==='overview'&&<div className='grid gap-6 md:grid-cols-2'><div className='space-y-5'><section><h3 className='mb-2 font-semibold'>Known allergies / alerts</h3>{allergyRecords.length?<div className='space-y-2'>{allergyRecords.map(r=><div key={r.id} className='rounded-xl border border-danger/20 bg-danger/5 p-3 text-sm'><b>{r.title}</b><p>{r.notes}</p></div>)}</div>:<p className='text-sm text-slate-400'>No allergy record is present in the accessible EHR.</p>}</section><section><h3 className='mb-2 font-semibold'>Recent clinical history</h3>{(records.data??[]).slice(0,8).map(r=><div key={r.id} className='mb-2 rounded-xl border border-border p-3 text-sm'><div className='flex justify-between'><b>{r.title}</b><span className='text-xs text-slate-400'>{formatDateTime(r.created_at)}</span></div>{r.diagnosis&&<p>{r.diagnosis}</p>}{r.notes&&<p className='text-slate-500'>{r.notes}</p>}</div>)}</section></div><AiTimelineSummarizer records={timeline}/></div>}
   {tab==='encounter'&&<div className='space-y-5'>{!canWrite&&<div className='rounded-xl border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800'>Read-only: start the clinical encounter before documenting care.</div>}
    <section className='rounded-xl border border-border p-4'><div className='mb-3 flex items-center gap-2'><IoPulseOutline/><h3 className='font-semibold'>Vitals</h3></div><div className='grid gap-3 sm:grid-cols-2 lg:grid-cols-4'>{['temperature_c','heart_rate_bpm','respiratory_rate_bpm','systolic_bp_mmhg','diastolic_bp_mmhg','oxygen_saturation_pct','weight_kg'].map(k=><Input key={k} label={VITAL_LABELS[k]} type='number' step='any' value={vitals[k]??''} onChange={e=>setVitals(v=>({...v,[k]:e.target.value}))}/>)}</div></section>
    <div className='grid gap-3 md:grid-cols-2'><Input label='Encounter title' value={title} onChange={e=>setTitle(e.target.value)}/><Input label='Diagnosis / working diagnosis' value={diagnosis} onChange={e=>setDiagnosis(e.target.value)}/></div>
    {[['Subjective / history',subjective,setSubjective],['Objective / examination',objective,setObjective],['Assessment / clinical reasoning',assessment,setAssessment],['Care plan',carePlan,setCarePlan],['General clinical notes',notes,setNotes]].map(([label,value,setter])=><label key={String(label)} className='block text-sm font-medium'>{String(label)}<textarea className='mt-1 min-h-20 w-full rounded-xl border border-border bg-white px-3 py-2 text-sm dark:bg-slate-900' value={String(value)} onChange={e=>(setter as (v:string)=>void)(e.target.value)}/></label>)}
    <section className='rounded-xl border border-border p-4'><h3 className='mb-3 font-semibold'>Prescription</h3>{items.map((x,i)=><div key={i} className='mb-2 flex justify-between rounded-lg bg-surface-muted p-3 text-sm'><span><b>{x.medicine_name}</b> · {x.dosage} · {x.frequency} · {x.duration_days} days</span><Button size='sm' variant='danger' onClick={()=>setItems(a=>a.filter((_,j)=>j!==i))}>Remove</Button></div>)}<div className='grid gap-3 sm:grid-cols-2'><div className='relative'><Input label='Medicine' value={medQuery} onChange={e=>setMedQuery(e.target.value)}/>{medQuery.length>2&&!selectedMed&&<div className='absolute z-10 mt-1 max-h-40 w-full overflow-y-auto rounded-xl border bg-white dark:bg-slate-800'>{(meds.data??[]).map(m=><button type='button' className='block w-full p-2 text-left text-sm' key={m.id} onClick={()=>{setSelectedMed(m);setMedQuery(m.name)}}>{m.name}</button>)}</div>}</div><Input label='Dosage' value={dosage} onChange={e=>setDosage(e.target.value)}/><Input label='Frequency' value={frequency} onChange={e=>setFrequency(e.target.value)}/><Input label='Duration days' type='number' min='1' value={duration} onChange={e=>setDuration(e.target.value)}/><Input label='Instructions' value={instructions} onChange={e=>setInstructions(e.target.value)}/></div><Button size='sm' variant='secondary' className='mt-3' onClick={addMedicine} disabled={!selectedMed||!dosage||!frequency}>Add medicine</Button><textarea className='mt-3 min-h-16 w-full rounded-xl border border-border p-2 text-sm' value={rxNotes} onChange={e=>setRxNotes(e.target.value)} placeholder='Prescription notes'/></section>
    <section className='rounded-xl border border-border p-4'><h3 className='mb-3 font-semibold'>Follow-up</h3><div className='grid gap-3 sm:grid-cols-2'><Input label='Follow-up date/time' type='datetime-local' value={followUpAt} onChange={e=>setFollowUpAt(e.target.value)}/><Input label='Instructions' value={followUpInstructions} onChange={e=>setFollowUpInstructions(e.target.value)}/></div></section>
    <section className='rounded-xl border border-border p-4'><h3 className='mb-3 font-semibold'>Laboratory order</h3><div className='grid gap-3 sm:grid-cols-2'><Select label='Verified laboratory' value={labId} onChange={e=>setLabId(e.target.value)}><option value=''>Select laboratory</option>{(labs.data??[]).map(l=><option key={l.id} value={l.id}>{l.name}{l.city?' · '+l.city:''}</option>)}</Select><Select label='Priority' value={priority} onChange={e=>setPriority(e.target.value)}><option value='low'>Low</option><option value='standard'>Standard</option><option value='high'>High</option><option value='critical'>Critical</option></Select></div><div className='mt-3 grid gap-2 sm:grid-cols-2'>{(tests.data??[]).map(t=><label key={t.id} className='flex gap-2 rounded-lg border border-border p-3 text-sm'><input type='checkbox' checked={selectedTests.includes(t.id)} onChange={()=>setSelectedTests(a=>a.includes(t.id)?a.filter(x=>x!==t.id):[...a,t.id])}/><span><b>{t.name}</b> <span className='text-xs text-slate-400'>{t.code}</span></span></label>)}</div><Button size='sm' className='mt-3' loading={order.isPending} disabled={!canWrite||!labId||!selectedTests.length} onClick={()=>order.mutate({appointmentId,labId,priority,testIds:selectedTests})}>Create lab order</Button></section>
    <div className='flex justify-end border-t border-border pt-4'><Button loading={save.isPending} disabled={!canWrite} onClick={saveEncounter}>Complete encounter & save</Button></div></div>}
   {tab==='labs'&&<div className='space-y-3'>{(reports.data??[]).map(r=><div key={r.id} className='rounded-xl border border-border p-4'><div className='flex justify-between'><b>{r.test_name??'Laboratory report'}</b><Badge tone={r.status==='verified'?'success':'neutral'}>{r.status}</Badge></div><p className='text-xs text-slate-400'>{r.report_code} · {formatDateTime(r.created_at)}</p><pre className='mt-2 whitespace-pre-wrap text-xs'>{JSON.stringify(r.result_json,null,2)}</pre></div>)}</div>}
   {tab==='prescriptions'&&<div className='space-y-3'>{(prescriptions.data??[]).map(r=><div key={r.id} className='rounded-xl border border-border p-4'><b>Prescription · {formatDateTime(r.created_at)}</b>{r.notes&&<p>{r.notes}</p>}{r.prescription_items?.map((i:any)=><p key={i.id} className='text-sm text-slate-500'>{i.medicines?.name||'Unknown medicine'} · {i.dosage} · {i.frequency} · {i.duration_days} days</p>)}</div>)}</div>}
  </div></Modal>;
}