/// <reference lib="webworker" />
declare const self: ServiceWorkerGlobalScope;

import { clientsClaim } from'workbox-core';
import { precacheAndRoute, createHandlerBoundToURL } from'workbox-precaching';
import { NavigationRoute, registerRoute } from'workbox-routing';
import { NetworkFirst, StaleWhileRevalidate, CacheFirst } from'workbox-strategies';
import { BackgroundSyncPlugin } from'workbox-background-sync';
import { CacheableResponsePlugin } from'workbox-cacheable-response';
import { ExpirationPlugin } from'workbox-expiration';

void self.skipWaiting();
clientsClaim();

// Precache resources generated by vite-plugin-pwa
precacheAndRoute(self.__WB_MANIFEST);

// App shell fallback
const handler = createHandlerBoundToURL('/offline.html');
const navigationRoute = new NavigationRoute(handler, {
 denylist: [/^\/api/, /^\/login/, /^\/$/],
});
registerRoute(navigationRoute);

// Runtime caching for Supabase Reads (StaleWhileRevalidate)
registerRoute(
 ({ url }) => url.hostname.endsWith('.supabase.co') && url.pathname.startsWith('/rest/v1'),
 new StaleWhileRevalidate({
 cacheName:'api-reads',
 plugins: [
 new ExpirationPlugin({ maxEntries: 200, maxAgeSeconds: 86400 }),
 new CacheableResponsePlugin({ statuses: [0, 200] }),
 ],
 }),
'GET'
);

// Runtime caching for Supabase Storage (CacheFirst)
registerRoute(
 ({ url }) => url.hostname.endsWith('.supabase.co') && url.pathname.startsWith('/storage/v1'),
 new CacheFirst({
 cacheName:'storage',
 plugins: [
 new ExpirationPlugin({ maxEntries: 100, maxAgeSeconds: 604800 }),
 new CacheableResponsePlugin({ statuses: [0, 200] }),
 ],
 })
);

// Workbox Background Sync for mutations
// Queues offline POST/PATCH/DELETE requests and replays them when back online
const bgSyncPlugin = new BackgroundSyncPlugin('supabase-mutations-queue', {
 maxRetentionTime: 24 * 60 // Retry for max of 24 Hours (specified in minutes)
});

registerRoute(
 ({ url }) => url.hostname.endsWith('.supabase.co') && url.pathname.startsWith('/rest/v1'),
 new NetworkFirst({
 plugins: [bgSyncPlugin]
 }),
'POST'
);

registerRoute(
 ({ url }) => url.hostname.endsWith('.supabase.co') && url.pathname.startsWith('/rest/v1'),
 new NetworkFirst({
 plugins: [bgSyncPlugin]
 }),
'PATCH'
);

registerRoute(
 ({ url }) => url.hostname.endsWith('.supabase.co') && url.pathname.startsWith('/rest/v1'),
 new NetworkFirst({
 plugins: [bgSyncPlugin]
 }),
'DELETE'
);
